version: "3.7"

services:
  fastapi:
    container_name: fastapi_app
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
