version: "3.7"

services:
  db:
    image: postgres:16-alpine
    container_name: db_app
    hostname: db_app
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: on-failure
    expose:
      - "5432"

volumes:
  pg_data:
