services:
  db:
    image: postgres:16-alpine
    env_file:
      - .env
    volumes:
      - pg_data:/var/lib/postgresql/data
    restart: unless-stopped
    ports:
      - "5432:5432"

  redis:
    build:
      context: .
      dockerfile: docker/redis.Dockerfile
    env_file:
      - .env
    volumes:
      - redis_data:/var/lib/redis/data
    restart: unless-stopped
    ports:
      - "6379:6379"

  fastapi:
    build:
      context: .
      dockerfile: docker/fastapi.Dockerfile
      target: prod
    env_file:
      - .env
    restart: unless-stopped
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
    volumes:
      - "./app:/opt/app/app"

volumes:
  pg_data:
  redis_data:
