"""empty message

Revision ID: fa7d22042c64
Revises: f2979d2bcb1c
Create Date: 2024-09-18 21:48:53.879568

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "fa7d22042c64"
down_revision: Union[str, None] = "f2979d2bcb1c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "users", sa.Column("telegram_id", sa.BigInteger(), nullable=True)
    )
    op.create_index(
        op.f("users_telegram_id_idx"), "users", ["telegram_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("users_telegram_id_idx"), table_name="users")
    op.drop_column("users", "telegram_id")
    # ### end Alembic commands ###
