"""empty message

Revision ID: 2cf5f1aeaeb8
Revises: cd31b0826b48
Create Date: 2024-08-13 14:25:47.280450

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "2cf5f1aeaeb8"
down_revision: Union[str, None] = "cd31b0826b48"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "roles_permissions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("role_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("permission_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_permissions_pkey")),
    )
    op.create_index(
        op.f("roles_permissions_permission_id_idx"),
        "roles_permissions",
        ["permission_id"],
        unique=True,
    )
    op.create_index(
        op.f("roles_permissions_role_id_idx"),
        "roles_permissions",
        ["role_id"],
        unique=True,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("roles_permissions_role_id_idx"), table_name="roles_permissions"
    )
    op.drop_index(
        op.f("roles_permissions_permission_id_idx"),
        table_name="roles_permissions",
    )
    op.drop_table("roles_permissions")
    # ### end Alembic commands ###
