"""empty message

Revision ID: 1e48ad2bb829
Revises: 2cf5f1aeaeb8
Create Date: 2024-08-13 14:34:18.598014

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "1e48ad2bb829"
down_revision: Union[str, None] = "2cf5f1aeaeb8"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "roles_permissions_permission_id_idx", table_name="roles_permissions"
    )
    op.create_index(
        op.f("roles_permissions_permission_id_idx"),
        "roles_permissions",
        ["permission_id"],
        unique=False,
    )
    op.drop_index(
        "roles_permissions_role_id_idx", table_name="roles_permissions"
    )
    op.create_index(
        op.f("roles_permissions_role_id_idx"),
        "roles_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_unique_constraint(
        op.f("roles_permissions_role_id_key"),
        "roles_permissions",
        ["role_id", "permission_id"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("roles_permissions_role_id_key"),
        "roles_permissions",
        type_="unique",
    )
    op.drop_index(
        op.f("roles_permissions_role_id_idx"), table_name="roles_permissions"
    )
    op.create_index(
        "roles_permissions_role_id_idx",
        "roles_permissions",
        ["role_id"],
        unique=True,
    )
    op.drop_index(
        op.f("roles_permissions_permission_id_idx"),
        table_name="roles_permissions",
    )
    op.create_index(
        "roles_permissions_permission_id_idx",
        "roles_permissions",
        ["permission_id"],
        unique=True,
    )
    # ### end Alembic commands ###
