"""empty message

Revision ID: 032670530868
Revises: 1e48ad2bb829
Create Date: 2024-08-13 18:13:11.185620

"""

from typing import Sequence, Union

from alembic import op


# revision identifiers, used by Alembic.
revision: str = "032670530868"
down_revision: Union[str, None] = "1e48ad2bb829"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "roles_permissions_permission_id_idx", table_name="roles_permissions"
    )
    op.drop_index(
        "roles_permissions_role_id_idx", table_name="roles_permissions"
    )
    op.create_foreign_key(
        op.f("roles_permissions_permission_id_fkey"),
        "roles_permissions",
        "permissions",
        ["permission_id"],
        ["id"],
        ondelete="cascade",
    )
    op.create_foreign_key(
        op.f("roles_permissions_role_id_fkey"),
        "roles_permissions",
        "roles",
        ["role_id"],
        ["id"],
        ondelete="cascade",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        op.f("roles_permissions_role_id_fkey"),
        "roles_permissions",
        type_="foreignkey",
    )
    op.drop_constraint(
        op.f("roles_permissions_permission_id_fkey"),
        "roles_permissions",
        type_="foreignkey",
    )
    op.create_index(
        "roles_permissions_role_id_idx",
        "roles_permissions",
        ["role_id"],
        unique=False,
    )
    op.create_index(
        "roles_permissions_permission_id_idx",
        "roles_permissions",
        ["permission_id"],
        unique=False,
    )
    # ### end Alembic commands ###
