"""empty message

Revision ID: 9d66ac80082e
Revises: fa7d22042c64
Create Date: 2024-10-17 19:51:19.762241

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9d66ac80082e"
down_revision: Union[str, None] = "fa7d22042c64"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "apps",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("secret", sa.String(), nullable=False),
        sa.Column("redirect_uris", sa.String(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("apps_pkey")),
    )
    op.create_index(
        op.f("apps_user_id_idx"), "apps", ["user_id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("apps_user_id_idx"), table_name="apps")
    op.drop_table("apps")
    # ### end Alembic commands ###
