"""empty message

Revision ID: cd31b0826b48
Revises: 590f147f3dca
Create Date: 2024-08-07 22:40:05.585183

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "cd31b0826b48"
down_revision: Union[str, None] = "590f147f3dca"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "permissions",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("domain", sa.String(), nullable=False),
        sa.Column("task", sa.String(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("permissions_pkey")),
        sa.UniqueConstraint(
            "domain", "task", name=op.f("permissions_domain_key")
        ),
    )
    op.create_index(
        op.f("permissions_domain_idx"), "permissions", ["domain"], unique=False
    )
    op.create_index(
        op.f("permissions_task_idx"), "permissions", ["task"], unique=False
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("name", sa.String(), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("roles_pkey")),
    )
    op.create_index(op.f("roles_name_idx"), "roles", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("roles_name_idx"), table_name="roles")
    op.drop_table("roles")
    op.drop_index(op.f("permissions_task_idx"), table_name="permissions")
    op.drop_index(op.f("permissions_domain_idx"), table_name="permissions")
    op.drop_table("permissions")
    # ### end Alembic commands ###
