"""empty message

Revision ID: 5781ebeb542c
Revises: bd54ebc87d2a
Create Date: 2024-09-09 17:55:03.266529

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "5781ebeb542c"
down_revision: Union[str, None] = "bd54ebc87d2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "sso_accounts",
        sa.Column("id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("user_id", sa.Uuid(as_uuid=False), nullable=False),
        sa.Column("provider", sa.String(), nullable=False),
        sa.Column("account_id", sa.String(), nullable=False),
        sa.Column("access_token", sa.String(), nullable=False),
        sa.Column("expires_in", sa.BigInteger(), nullable=True),
        sa.Column("scope", sa.String(), nullable=True),
        sa.Column("id_token", sa.String(), nullable=True),
        sa.Column("refresh_token", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("first_name", sa.String(), nullable=True),
        sa.Column("last_name", sa.String(), nullable=True),
        sa.Column("display_name", sa.String(), nullable=True),
        sa.Column("picture", sa.String(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id", name=op.f("sso_accounts_pkey")),
    )
    op.create_index(
        op.f("sso_accounts_email_idx"), "sso_accounts", ["email"], unique=False
    )
    op.create_index(
        op.f("sso_accounts_user_id_idx"),
        "sso_accounts",
        ["user_id"],
        unique=False,
    )
    op.drop_index("oidc_accounts_email_idx", table_name="oidc_accounts")
    op.drop_index("oidc_accounts_user_id_idx", table_name="oidc_accounts")
    op.drop_table("oidc_accounts")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "oidc_accounts",
        sa.Column("id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column("user_id", sa.UUID(), autoincrement=False, nullable=False),
        sa.Column(
            "provider", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "access_token", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.Column(
            "id_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "refresh_token", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("email", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "first_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "last_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column(
            "display_name", sa.VARCHAR(), autoincrement=False, nullable=True
        ),
        sa.Column("picture", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "created_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            postgresql.TIMESTAMP(),
            server_default=sa.text("now()"),
            autoincrement=False,
            nullable=False,
        ),
        sa.Column(
            "account_id", sa.VARCHAR(), autoincrement=False, nullable=False
        ),
        sa.PrimaryKeyConstraint("id", name="oidc_accounts_pkey"),
    )
    op.create_index(
        "oidc_accounts_user_id_idx", "oidc_accounts", ["user_id"], unique=False
    )
    op.create_index(
        "oidc_accounts_email_idx", "oidc_accounts", ["email"], unique=False
    )
    op.drop_index(op.f("sso_accounts_user_id_idx"), table_name="sso_accounts")
    op.drop_index(op.f("sso_accounts_email_idx"), table_name="sso_accounts")
    op.drop_table("sso_accounts")
    # ### end Alembic commands ###
